### PR TITLE
Update Consul dependency to v0.30.0 to allow use of Consul 1.0.x

### PR DESCRIPTION
**Pull request by grempe**
See : https://github.com/silas/node-consul/issues/64

### CODE REVIEW

**Comment by jacohend** [comment]
@spathon Wondering what the status was on this? Is this good to merge?

**Comment by spathon** [comment]
@jacohend you should probably check with @norla I don't really have anything to do with this repo or any rights any more.

**Comment by norla** [comment]
Sorry @jacohend  @grempe @spathon, had missed this PR. Merging!

**Comment by norla** [comment]
https://www.npmjs.com/package/exp-leader-election/v/0.3.0

**Pull request merged**
